trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Stage 1: Build Frontend
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: BuildJob
    displayName: 'Install & Build Frontend'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: npm install
      workingDirectory: 'client'
      displayName: 'Install Frontend Dependencies'

    - script: npm run build
      workingDirectory: 'client'
      displayName: 'Build Frontend'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'client/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true
      displayName: 'Archive Frontend Build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publish Frontend Artifact'

# Stage 2: Deploy to Azure
- stage: DeployFrontend
  displayName: 'Deploy Frontend to Azure'
  dependsOn: BuildFrontend
  jobs:
  - job: DeployJob
    displayName: 'Deploy to Azure Web App'
    steps:
    - download: current
      artifact: frontend

    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students (bedc7931-d790-4c13-b257-15a58fdfea2f)'
        appType: 'webAppLinux'
        WebAppName: 'edusync-frontend'
        packageForLinux: '$(Pipeline.Workspace)/frontend/frontend.zip'
      displayName: 'Deploy Frontend to Azure Web App'