trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Stage 1: Build Frontend
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: BuildJob
    displayName: 'Install & Build Frontend'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js 16.x'

    - script: npm ci
      workingDirectory: 'client'
      displayName: 'Clean Install Frontend Dependencies'

    - script: npm run build
      workingDirectory: 'client'
      displayName: 'Build Frontend Project'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'client/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true
      displayName: 'Archive Frontend Build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
      displayName: 'Publish Frontend Artifact'
